package view;

import controller.ControllerEditKereta;
import model.Kereta;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class EditKereta extends javax.swing.JFrame {
    String asal, tujuan, jam_berangkat, jam_sampai;
    int harga, kapasitas, indexTujuan, indexJam;
    ControllerEditKereta cEdit;
    Kereta kereta1;
    
    public EditKereta() {
        dispose();
    }
    
    public EditKereta(Kereta arg) {
        initComponents();
        kereta1 = arg;
        cEdit = new ControllerEditKereta(this);
        cEdit.tampilkanData(kereta1);
    }
    public JTextField getTxtHarga(){
        return txtHarga;
    }
    public JTextField getTxtKapasitas(){
        return txtKapasitas;
    }
    public String getAsal(){
        return this.asal;
    }
    public String getTujuan(){
        return this.tujuan;
    }
    public String getJamBerangkat(){
        return this.jam_berangkat;
    }
    public String getJamSampai(){
        return this.jam_sampai;
    }
    
    public void setTxtHarga(String harga){
        txtHarga.setText(harga);
    }
    public void setTxtKapasitas(String kapasitas){
        txtKapasitas.setText(kapasitas);
    }
    public void setIndexTujuan(String tujuan){
        if(tujuan.equals("Jakarta")){
            this.indexTujuan = 0;
        }
        else if(tujuan.equals("Surabaya")){
            this.indexTujuan = 1;
        }
        else if(tujuan.equals("Semarang")){
            this.indexTujuan = 2;
        }
        else {
            this.indexTujuan = 3;
        }
        sJurusan.setSelectedIndex(indexTujuan);
    }
    public void setIndexJam(String jam_berangkat){
        if(jam_berangkat.equals("06.25")){
            this.indexJam = 0;
        }
        else if(jam_berangkat.equals("10.00")){
            this.indexJam = 1;
        }
        else if(jam_berangkat.equals("15.00")){
            this.indexJam = 2;
        }
        else {
            this.indexJam = 3;
        }
        sJam.setSelectedIndex(indexJam);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sJurusan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sJam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Edit Kereta");

        jLabel2.setText("Jurusan");

        sJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jogja - Jakarta", "Jogja - Surabaya", "Jogja - Semarang", "Jogja - Solo" }));
        sJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sJurusanActionPerformed(evt);
            }
        });

        jLabel3.setText("Jam");

        sJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06.25 - 07.25", "10.00 - 11.00", "15.00 - 16.00", "19.00 - 20.00" }));
        sJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sJamActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga");

        jLabel5.setText("Kapasitas");

        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Save.setText("Simpan");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sJurusan, 0, 152, Short.MAX_VALUE)
                                    .addComponent(sJam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHarga)
                                    .addComponent(txtKapasitas))))
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Save))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sJurusanActionPerformed
       if(sJurusan.getSelectedItem().equals("Jogja - Jakarta")){
            this.asal = "Jogja";
            this.tujuan = "Jakarta";
        }
        else if(sJurusan.getSelectedItem().equals("Jogja - Surabaya")){
            this.asal = "Jogja";
            this.tujuan = "Surabaya";
        }
        else if(sJurusan.getSelectedItem().equals("Jogja - Semarang")){
            this.asal = "Jogja";
            this.tujuan = "Semarang";
        } else {
            this.asal = "Jogja";
            this.tujuan = "Solo";
        }
    }//GEN-LAST:event_sJurusanActionPerformed

    private void sJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sJamActionPerformed
      if(sJam.getSelectedItem().equals("06.25 - 07.25")){
            this.jam_berangkat = "06.25";
            this.jam_sampai = "07.25";
        } 
        else if(sJam.getSelectedItem().equals("10.00 - 11.00")){
            this.jam_berangkat = "10.00";
            this.jam_sampai = "11.00";
        } 
        else if(sJam.getSelectedItem().equals("15.00 - 16.00")){
            this.jam_berangkat = "15.00";
            this.jam_sampai = "16.00";
        } else {
            this.jam_berangkat = "19.00";
            this.jam_sampai = "20.00";
        }
    }//GEN-LAST:event_sJamActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        cEdit.kembali();
    }//GEN-LAST:event_backActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        cEdit.simpanEdit(kereta1.getId());
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditKereta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> sJam;
    private javax.swing.JComboBox<String> sJurusan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKapasitas;
    // End of variables declaration//GEN-END:variables
}
